# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow:
    has_velocity_limits: true
    max_velocity: 25.0
    has_acceleration_limits: true
    max_acceleration: 25.0
  hand_roll:
    has_velocity_limits: true
    max_velocity: 25.0
    has_acceleration_limits: true
    max_acceleration: 25.0
  shoulder:
    has_velocity_limits: true
    max_velocity: 25.0
    has_acceleration_limits: true
    max_acceleration: 25.0
  waist:
    has_velocity_limits: true
    max_velocity: 25.0
    has_acceleration_limits: true
    max_acceleration: 25.0
  wrist_flex:
    has_velocity_limits: true
    max_velocity: 25.0
    has_acceleration_limits: true
    max_acceleration: 25.0
  wrist_rotation:
    has_velocity_limits: true
    max_velocity: 25.0
    has_acceleration_limits: true
    max_acceleration: 25.0

cartesian_limits:
  max_trans_vel: 0.25
  max_trans_acc: 1.5
  max_trans_dec: -25.0
  max_rot_vel: 1.57