merlin:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - waist
      - shoulder
      - elbow
      - wrist_rotation
      - wrist_flex
      - hand_roll
    state_publish_rate:  25
    action_monitor_rate: 10