merlin:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - waist
      - shoulder
      - elbow
      - wrist_rotation
      - wrist_flex
      - hand_roll
    gains: # Required because we're controlling a velocity interface
      waist: {p: 1,  d: 0, i: 0, i_clamp: 0}
      shoulder: {p: 1,  d: 0, i: 0, i_clamp: 0}
      elbow: {p: 1,  d: 0, i: 0, i_clamp: 0}
      wrist_rotation: {p: 1,  d: 0, i: 0, i_clamp: 0}
      wrist_flex: {p: 1,  d: 0, i: 0, i_clamp: 0}
      hand_roll: {p: 1,  d: 0, i: 0, i_clamp: 0}

    state_publish_rate:  25
    action_monitor_rate: 10