# merlin:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: pos_vel_controllers/JointTrajectoryController 
  joints:
    - waist
    - shoulder
    - elbow
    - wrist_rotation
    - wrist_flex
    - hand_roll
  # Update with real motor precision limits 
  # constraints:
  #   # goal_time: 2.5
  #   waist: 
  #     #trajectory: 0.1745
  #     goal: 0.05
  #   shoulder: 
  #     #trajectory: 0.1745
  #     goal: 0.05
  #   elbow: 
  #     #trajectory: 0.1745
  #     goal: 0.05
  #   wrist_rotation:
  #     #trajectory: 0.1745
  #     goal: 0.05
  #   wrist_flex:
  #     #trajectory: 0.1745
  #     goal: 0.05
  #   hand_roll:
  #     #trajectory: 0.1745
  #     goal: 0.05
 
  # Required to define because we're controlling a velocity interface but not 
  # used since we directly set the velocity in the hardware interface   
  gains:
    waist:          {p: 1,  d: 0, i: 0, i_clamp: 1}
    shoulder:       {p: 1,  d: 0, i: 0, i_clamp: 1}
    elbow:          {p: 1,  d: 0, i: 0, i_clamp: 1}
    wrist_rotation: {p: 1,  d: 0, i: 0, i_clamp: 1}
    wrist_flex:     {p: 1,  d: 0, i: 0, i_clamp: 1}
    hand_roll:      {p: 1,  d: 0, i: 0, i_clamp: 1}

