joint_limits:
  waist:
    has_position_limits: true
    min_position: 0
    max_position: 5.06145
    has_velocity_limits: true
    max_velocity: 0.314159 #0.15708
    has_acceleration_limits: true
    max_acceleration: 0.0785398

  elbow: # TODO: Explicitly define limits 
    has_velocity_limits: true
    max_velocity: 0.314159 #0.15708
    has_acceleration_limits: true
    max_acceleration: 0.0785398

  shoulder:
    has_velocity_limits: true
    max_velocity: 0.314159 #0.15708
    has_acceleration_limits: true
    max_acceleration: 0.0785398

  wrist_rotation:
    has_velocity_limits: true
    max_velocity: 0.314159 #0.15708
    has_acceleration_limits: true
    max_acceleration: 0.0785398

  wrist_flex:
    has_position_limits: true
    min_position: -1.5708
    max_position: 1.5708
    has_velocity_limits: true
    max_velocity: 0.314159 #0.15708
    has_acceleration_limits: true
    max_acceleration: 0.0785398

  hand_roll:
    has_velocity_limits: true
    max_velocity: 0.314159 #0.15708
    has_acceleration_limits: true
    max_acceleration: 0.0785398

