controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController 

position_trajectory_controller:
  ros__parameters:
    joints:
      - merlin_joint_0
      - merlin_joint_1
      - merlin_joint_2
      - merlin_joint_3
      - merlin_joint_4
      - merlin_joint_5
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

forward_position_controller:
  ros__parameters:
    joints:
      - merlin_joint_0
      - merlin_joint_1
      - merlin_joint_2
      - merlin_joint_3
      - merlin_joint_4
      - merlin_joint_5
    interface_name: position
