controller_manager:
  ros__parameters:
    update_rate: 600  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    plate_position_controller:
      type: position_controllers/JointTrajectoryController
      joint: plate_rotation
    
    # joint_state_controller:
    #   type: joint_state_controller/JointStateController
    #   publish_rate: 60

plate_position_controller:
  ros__parameters:
    joints:
      - plate_rotation
    
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

arm_trajectory_controller:
  ros__parameters:
    joints:
      - merlin_joint_0
      - merlin_joint_1
      - merlin_joint_2
      - merlin_joint_3
      - merlin_joint_4
      - merlin_joint_5
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
