controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - waist_joint
      - shoulder_joint
      - elbow_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: rest