# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.01
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  merlin_joint_0:
    has_position_limits: true
    min_position: -4.537856
    max_position: 0.523599
    has_velocity_limits: true
    max_velocity: 0.523599 
    has_acceleration_limits: true
    max_acceleration: 1.570796

  merlin_joint_1:
    has_velocity_limits: true
    max_velocity: 0.523599 
    has_acceleration_limits: true
    max_acceleration: 1.570796
    
  merlin_joint_2: # TODO: Replace placeholder limits 
    has_position_limits: true
    min_position: -3.14159
    max_position: 3.14159
    has_velocity_limits: true
    max_velocity: 0.523599 
    has_acceleration_limits: true
    max_acceleration: 1.570796

  merlin_joint_3:
    has_velocity_limits: true
    max_velocity: 0.785398
    has_acceleration_limits: true
    max_acceleration: 1.570796

  merlin_joint_4:
    has_position_limits: true
    min_position: -1.5708
    max_position: 1.5708
    has_velocity_limits: true
    max_velocity: 0.785398
    has_acceleration_limits: true
    max_acceleration: 1.570796

  merlin_joint_5:
    has_velocity_limits: true
    max_velocity: 0.785398
    has_acceleration_limits: true
    max_acceleration: 1.570796

