controller_names:
  - arm_trajectory_controller

# http://control.ros.org/ros2_controllers/joint_trajectory_controller/doc/userdoc.html#ros2-interface-of-the-controller
arm_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - merlin_joint_0
    - merlin_joint_1
    - merlin_joint_2
    - merlin_joint_3
    - merlin_joint_4
    - merlin_joint_5